### ISSUE TITLE
Inconsistent font sizes under descriptions on Experience page

### ISSUE THREAD

**Issue by varunrajan** [kennedysgarage/kennedysgarage#9]
On `_pages/experience.html`, some of the project/job descriptions have a `font-size` of `21px`, and other times `18px`. Not sure if this is on purpose, but it looks a bit jarring.

Looks like every project description the `"intro"` class is meant to render as 21px: https://github.com/kennedysgarage/kennedysgarage/blob/3df46a90ea2b3e43c747644a96c7f559e6dde462/_assets/css/style.css.scss#L180-L182

But in some cases, the styles for paragraph and list elements nested under `"project"` class elements seem to override this:

The code:
https://github.com/kennedysgarage/kennedysgarage/blob/3df46a90ea2b3e43c747644a96c7f559e6dde462/_assets/css/style.css.scss#L710-L713

The inspector where `.intro` is overriden:
![image](https://user-images.githubusercontent.com/8453161/67439022-203ff100-f5c3-11e9-91e8-275a034c72f4.png)

I'm afraid I don't know enough about CSS to help more, but it would be great to get the fonts consistent!

**Comment by kennedysgarage** [comment]
Great find. When I moved _Products_ under _Work_ I renamed _Products_ to _Projects_ because most of my work is products. So I had to include projects as a filter option. When I did that I forgot that the primary class name for a project page was _project_. Great find.
